### ISSUE TITLE
Update "How to Obtain S3 URLs" notebook

### ISSUE THREAD

**Issue by battistowx** [nasa/gesdisc-tutorials#120]

**Comment by alexishunzinger** [comment]
The original version of this notebook, [Obtain a List of S3 URLs for a GES DISC Collection Using the CMR API](https://github.com/nasa/gesdisc-tutorials/blob/main/cloud-tutorials/notebooks/How_to_Obtain_a_List_of_S3_URLs_for_a_GES_DISC_Collection_Using_the_CMR_API.ipynb) , used the Python `requests` library to interact with the CMR API. Since its original publishing (2022), updates to Python-based search and access methods are motivating us to:

1. reconsider the purpose of generating a list of S3 URLs - is an explicit list comprehension needed to perform data access in the cloud?
2. add the newer methods/packages to this How-To, including the advantages of each to help inform the user so they can choose which option is best for them
